INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3621, 'Matemática Discreta', '-', 4, 1, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3622, 'Análisis Matemático I	', '-', 4, 1, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3623, 'Programación Inicial	', '-', 4, 1, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3624, 'Introducción a los Sistemas de Información	', '-', 4, 1, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3625, 'Sistemas de Numeración	', '-', 4, 1, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3626, 'Principios de Calidad de Software', '-', 4, 1, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3627, 'Álgebra y Geometría Analítica I	', '-', 4, 1, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3628, 'Física I', 3622, 4, 1, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3629, 'Programación Estructurada Básica	', 3623, 4, 1, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3630, 'Introducción a la Gestión de Requisitos	', 3624, 4, 1, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3631, 'Fundamentos de Sistemas Embebidos', '3625	', 4, 1, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3632, 'Introducción a Proyectos Informáticos	', '-', 4, 1, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3633, 'Análisis Matemático II	', 3622, 4, 2, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3634, 'Física II', '3628	', 4, 2, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3635, 'Tópicos de Programación', '3629 / 3621	', 4, 2, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3636, 'Bases de Datos', '3629 / 3621	', 4, 2, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3637, 'Análisis de Sistemas', 3630, 4, 2, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3638, 'Arquitectura de Computadoras', 3631, 4, 2, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3639, 'Responsabilidad Social Universitaria	', 3626, 4, 2, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3640, 'Análisis Matemático III	', '3633	', 4, 2, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3641, 'Algoritmos y Estructuras de Datos	', '3635	', 4, 2, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3642, 'Bases de Datos Aplicada	', '3636	', 4, 2, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3643, 'Principios de Diseño de Sistemas	', '3637 / 3626', 4, 2, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3644, 'Redes de Computadoras	', '3638 / 3634	', 4, 2, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3645, 'Gestión de las Organizaciones	', 3632, 4, 2, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3646, 'Taller de Integración*	', '3638 / 3636 / 3635 / 3632 / 3630 / 3626 / 3625 / 3624 / 3623 / 3621', 4, 2, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3647, 'Álgebra y Geometría Analítica II	', 3627, 4, 3, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3648, 'Paradigmas de Programación	', '3640 / 3633	', 4, 3, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3649, 'Requisitos Avanzados	', 3642, 4, 3, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3650, 'Diseño de Software	', '3642 / 3636	', 4, 3, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3651, 'Sistemas Operativos	', 3638, 4, 3, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3652, 'Seguridad de la Información	', '3643 / 3638 / 3635	', 4, 3, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3653, 'Práctica Profesional Supervisada	', 3642, 4, 3, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3654, 'Probabilidad y Estadística	', '3645 / 3639 / 3621	', 4, 3, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3655, 'Programación Avanzada	', '3641 / 3646	', 4, 3, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3656, 'Arquitecturas de Sistemas Software	', 3648, 4, 3, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3657, 'Virtualización de Hardware	', '3649 / 3645 / 3640	', 4, 3, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3658, 'Auditoría y Legislación	', 3650, 4, 3, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3659, 'Estadística Aplicada	', '3651 / 3641	', 4, 4, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3660, 'Autómatas y Gramática	', 3646, 4, 4, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3661, 'Programación Concurrente	', '3654 / 3646	', 4, 4, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3662, 'Gestión Aplicada al Desarrollo de Software I	', '3653 / 3647 / 3644	', 4, 4, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3663, 'Sistemas Operativos Avanzados	', 3654, 4, 4, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3664, 'Gestión de Proyectos	', '3651 / 3650 / 3644	', 4, 4, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3665, 'Matemática Aplicada	', '3651	', 4, 4, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3666, 'Lenguajes y Compiladores	', 3657, 4, 4, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3667, 'Inteligencia Artificial	', '3651 / 3646	', 4, 4, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3668, 'Gestión Aplicada al Desarrollo de Software II	', '3659 / 3652	', 4, 4, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3669, 'Seguridad Aplicada y Forensia	', '3655 / 3652 / 3649	', 4, 4, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3670, 'Gestión de la Calidad en Procesos de Sistemas	', 3647, 4, 4, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3671, 'Inteligencia Artificial Aplicada	', '3664 / 3656	', 4, 5, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3672, 'Innovación y Emprendedorismo	', 3661, 4, 5, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3673, 'Ciencia de Datos	', '3664 / 3656	', 4, 5, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3674, 'Proyecto Final de Carrera**	', '3667 / 3661 / 3660 / 3659 / 3656	', 4, 5, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3675, 'Electiva I	', '3658 / 3661 / 3663	', 4, 5, 1);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3676, 'Electiva II	', '3662 / 3666	', 4, 5, 2);
INSERT INTO nombre_tabla (codigo, asignatura, correlatividad, horaas semanales, año, cuatrimestre) VALUES (3677, 'Electiva III	', '3664 / 3665	', 4, 5, 2);